### ISSUE TITLE
Rewrite animation names for humans

### ISSUE THREAD

**Issue by belozer** [bem-contrib/bem-animations#18]
## In AnimateCSS found the problem names for effects..

(good) `FadeInUp` - fade-in from down to up
(good) `FadeInDown` - fade-in from up to down
(good) `FadeOutUp` - fade-out to up
(good) `FadeOutDown` - fade-out to down

But... :bomb: 
__(bad!) `FadeInRight` - fade-in from right to left__
__(bad!) `FadeInLeft` - fade-in from left to right__
(good) `FadeOutRight` - fade-out to right
(good) `FadeOutLeft` - fade-out to left

This naming breaks the understanding in the other animations.
`bounce`, `slide`.

## bem-animations created for humans!
We should rewrite names for all problems.

**Comment by AleshaOleg** [comment]
The list of broken names: 
- bounceInLeft
- bounceInRight
- fadeInLeft
- fadeInLeftBig
- fadeInRight
- fadeInRightBig
- slideInLeft
- slideInRight
- zoomInLeft
- zoomInRight

**Comment by AleshaOleg** [comment]
Pull request here: #28

**Comment by AleshaOleg** [comment]
Created new pull request #30
